pub const MAX_FILE_IN_DIR = 1024;
pub const MAX_SPLIT_IN_SEQUENCE = 10;
pub const MAX_STR_ENTRY_LEN = 256;
pub const MAX_STR_PATTERN_LEN = 128;
pub const MAX_LEN_FOR_SEQUENCE_SPLIT = 512;
pub const MAX_DISPLAYED_ISOLATED_FILE = 3;
